name: Debian AArch64 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  debian-test:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --platform linux/arm64

    steps:
      - name: Install dependencies
        run: apt update && apt install -y git cmake make gcc

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ./jcc.sh ci-test

