name: Ubuntu RISC-V CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
              git \
              coreutils \
              lsb-release \
              python3 \
              python3-pip \
              autoconf \
              bc \
              bison \
              dos2unix \
              gdb \
              gcc \
              lcov \
              make \
              flex \
              build-essential \
              ca-certificates \
              curl \
              device-tree-compiler \
              lcov \
              nano \
              valgrind \
              clang \
              bear

      - name: Install RISC-V GNU Toolchain
        run: |
          curl --output riscv-gnu-toolchain.tar.gz -L "https://github.com/langproc/langproc-2022-cw/releases/download/v1.0.0/riscv-gnu-toolchain-2022-09-21-ubuntu-22.04-amd64.tar.gz"
          rm -rf /opt/riscv
          tar -xzf riscv-gnu-toolchain.tar.gz --directory /opt
          rm -rf riscv-gnu-toolchain.tar.gz

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install riscy
        run: cargo install risc-y

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          PATH="/opt/riscv/bin:${PATH}" \
          RISCV="/opt/riscv" \
          RUNNER=riscy \
            ./jcc.sh ci-test -target rv32i-unknown-elf -- -isysroot /opt/riscv -isystem /opt/riscv/riscv64-unknown-elf/include



